AdvancedSoftwareDevelopment/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('', include('django.contrib.auth.urls')),
    url('', include('webshop.urls', namespace='webshop')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webshop/urls.py
from django.conf.urls import url
from . import views

app_name ='webshop'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', views.logout_view, {'next_page': 'pages/login'}, name='logout'),
    url(r'^product/$', views.product_list_view, name='product-list'),
    url(r'^product/(?P<productID>\d+)/$', views.product_detail_view, name='product-details'),
    url(r'^cart/$', views.get_cart, name='cart'),
    url(r'^add_to_cart/(\d+)/$', views.add_to_cart, name='add_to_cart'),
    url(r'^remove_from_cart/(\d+)/$', views.remove_from_cart, name='remove_from_cart'),
    url(r'^increase_in_cart/(\d+)/(\d+)/$', views.increase_in_cart, name='increase_in_cart'),
    url(r'^decrease_in_cart/(\d+)/(\d+)/$', views.decrease_in_cart, name='decrease_in_cart'),
    url(r'^product_search_list_view/$', views.product_search_list_view, name='product_search_list_view'),
    url(r'^buy/$', views.purchase, name='Buy'),
    url(r'^my_orders/$', views.order_view, name='orders')
]

webshop/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings


class Product(models.Model):
    name = models.CharField(max_length=100)
    height = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(0)])
    price = models.DecimalField(max_digits=18, decimal_places=2, validators=[MinValueValidator(0)])
    description = models.CharField(max_length=500)
    stock = models.PositiveIntegerField(default=10)
    errortext = models.CharField(max_length=100, blank=True, default='', editable=False)

    NO_DISCOUNT = '-'
    THREE_FOR_TWO = '3 for 2'
    TWO_FOR_1 = '2 for 1'
    SEVENTY_PERCENT = '70%'
    SIXTY_PERCENT = '60%'
    FIFTY_PERCENT = '50%'
    FORTY_PERCENT = '40%'
    THIRTY_PERCENT = '30%'
    TWENTY_PERCENT = '20%'
    TEN_PERCENT = '10%'
    FIVE_PERCENT = '5%'

    DISCOUNT_CHOICES = (
        (NO_DISCOUNT, 'no discount'),
        (THREE_FOR_TWO, '3 for 2'),
        (TWO_FOR_1, '2 for 1'),
        (SEVENTY_PERCENT, '70%'),
        (SIXTY_PERCENT, '60%'),
        (FIFTY_PERCENT, '50%'),
        (FORTY_PERCENT, '40%'),
        (THIRTY_PERCENT, '30%'),
        (TWENTY_PERCENT, '20%'),
        (TEN_PERCENT, '10%'),
        (FIVE_PERCENT, '5%')
    )

    NO_BRAND = '-'
    APOLLO = 'APPOLLO'
    ROSCOCOSMOS = 'ROSCOCOSMOS'
    SpaceX = 'SpaceX'
    VOLVO = 'VOLVO'
    DBS = 'DBS'

    BRAND_CHOICES = (
        (NO_BRAND, '-'),
        (APOLLO, 'APOLLO'),
        (ROSCOCOSMOS, 'ROSCOCOSMOS'),
        (SpaceX, 'SpaceX'),
        (VOLVO, 'VOLVO'),
        (DBS, 'DBS')
    )

    NO_COUNTRY = '-'
    USA = 'US&A'
    RASSIA = 'Rassia'
    NORTHKOREA = 'North Korea'
    SOUTHTRONDELAG = 'South Trondelag'

    COUNTRY_CHOICES = (
        (NO_COUNTRY, '-'),
        (USA, 'US&A'),
        (RASSIA, 'Rassia'),
        (NORTHKOREA, 'North Korea'),
        (SOUTHTRONDELAG, 'South Trondelag')
    )

    brand = models.CharField(max_length=11, choices=BRAND_CHOICES, default=NO_BRAND)
    country = models.CharField(max_length=30, choices=COUNTRY_CHOICES, default=NO_COUNTRY)
    discount = models.CharField(max_length=11, choices=DISCOUNT_CHOICES, default=NO_DISCOUNT)

    def __str__(self):
        return self.name

    def get_discounted_price(self):
        discounted_price = self.price
        if '%' in self.discount:
            discount_percent = int(self.discount.split('%')[0])
            discounted_price = self.price - (self.price * discount_percent / 100)
        return discounted_price

    def has_discounted_price(self):
        return self.get_discounted_price() < self.price

    def has_package_deal(self):
        return 'for' in self.discount


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    ORDER_CONFIRMED = 'Order confirmed'
    ORDER_ACCEPTED = 'Order accepted'
    READY_FOR_TRANSPORTATION = 'Order ready for transportation'
    ORDER_SENT = 'Order sent'

    STATUS_CHOICES = (
        (ORDER_CONFIRMED, 'Order confirmed'),
        (ORDER_ACCEPTED, 'Order accepted'),
        (READY_FOR_TRANSPORTATION, 'Order ready for transportation'),
        (ORDER_SENT, 'Order sent')
    )
    status_field = models.CharField(max_length=30, choices=STATUS_CHOICES, default=ORDER_CONFIRMED)

    # helper field to compare status before and after an order update
    __original_status = None

    def __init__(self, *args, **kwargs):
        super(Order, self).__init__(*args, **kwargs)
        self.__original_status = self.status_field

    # override save method to be able to check if status field has been updated
    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.status_field != self.__original_status:
            self.send_update_email()
        super(Order, self).save(force_insert, force_update, *args, **kwargs)
        self.__original_status = self.status_field

    # send update email to user when the status of an order has been updated
    def send_update_email(self):
        send_mail(
            'Your order at SkyIsNotTheLimit has changed',
            'Hello!\n\nYour order at SkyIsNotTheLimit has changed status. '
            'Log in and see my orders for more details.',
            settings.EMAIL_HOST_USER,
            [self.user.username],
            fail_silently=False
        )

    def __str__(self):
        return str(self.id)


class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)


# Helper class for getting the items in the cart
class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)


# An Item represents an entry in the shopping cart
class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('cart'), on_delete=models.CASCADE,)
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE,)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

    def get_discounted_price(self):
        return self.product.get_discounted_price()

    def get_package_deal_price(self, total_price):
        if self.product.has_package_deal():
            multiple = self.quantity // int(self.product.discount[0])
            return total_price - (multiple * self.unit_price)
        return total_price

    def total_price(self):
        total_price = self.quantity * self.unit_price
        if self.product.has_discounted_price():
            total_price = self.quantity * self.get_discounted_price()
        elif self.product.has_package_deal():
            total_price = self.get_package_deal_price(total_price)
        return total_price
    total_price = property(total_price)

webshop/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from webshop.cart import Cart
from webshop.models import Product, Order
import webshop.models as models
from functools import reduce
from django.db.models import Q
import operator
from django.core.mail import send_mail
from django.conf import settings


@login_required
def index(request):
    return render(request, 'pages/index.html')


def logout_view(request):
    logout(request)
    return redirect('pages/login')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('webshop:index')
    else:
        form = UserCreationForm()
    return render(request, 'pages/signup.html', {'form': form})


@login_required
def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    if product.stock >= 1:
        cart = Cart(request)
        cart.add(product, product.price, 1)
        product.errortext = ''
        product.save()
        return redirect('webshop:cart')
    product.errortext = 'Not enough items available in stock!'
    product.save()
    return redirect('webshop:product-list')


@login_required
def remove_from_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    cart = Cart(request)
    cart.remove(product)
    return redirect('webshop:cart')


@login_required
def order_view(request):
    current_user = request.user
    order_list = Order.objects.filter(user=current_user)
    return render(request, 'pages/order-list.html', {'order_list': order_list})


def add_order(product, user):
    order = models.Order(product=product, user=user)
    order.save()


def update_stock(product, quantity):
    product.stock = product.stock - quantity
    product.save()


def send_confirmation_email(user):
    send_mail(
        'Your purchase at SkyIsNotTheLimit',
        'Hello!\n\nYour purchase at SkyIsNotTheLimit is confirmed. Se my orders for more details.',
        settings.EMAIL_HOST_USER,
        [user.username],
        fail_silently=False
    )


@login_required
def purchase(request):  # update stock, clear cart and send confirmation email to the user
    cart = Cart(request)
    products_in_cart = cart.get_products()

    for item in products_in_cart:
        product = Product.objects.get(id=item.product.id)

        update_stock(product, item.quantity)
        add_order(product, request.user)

    cart.clear()
    send_confirmation_email(request.user)

    return render(request, 'pages/purchase-completed.html')


@login_required
def increase_in_cart(request, product_id, quantity):
    product = Product.objects.get(id=product_id)
    quantity = int(quantity) + 1
    if product.stock >= quantity:
        cart = Cart(request)
        cart.update(product, quantity, product.price)
    return redirect('webshop:cart')


@login_required
def decrease_in_cart(request, product_id, quantity):
    product = Product.objects.get(id=product_id)
    cart = Cart(request)
    quantity = int(quantity) - 1
    cart.update(product, quantity, product.price)
    return redirect('webshop:cart')


@login_required
def get_cart(request):
    return render(request, 'pages/cart.html', dict(cart=Cart(request)))


@login_required
def product_list_view(request):
    product_list = Product.objects.all()

    return render(request, 'pages/product-list.html', {'product_list': product_list})


@login_required
def product_detail_view(request, productID):
    product = Product.objects.get(id=productID)
    discounted_price = product.get_discounted_price()
    return render(request, 'pages/product-details.html', {'product': product, 'discounted_price': discounted_price})


@login_required
def product_search_list_view(request):
    result = Product.objects.all()
    query_text = request.GET.get('q')
    query_min_price = request.GET.get('minprice')
    query_max_price = request.GET.get('maxprice')
    if query_text:
        query_list = query_text.split()
        result = result.filter(
            reduce(operator.and_,
                   (Q(brand__icontains=q) for q in query_list)) |
            reduce(operator.and_,
                   (Q(description__icontains=q) for q in query_list)) |
            reduce(operator.and_,
                   (Q(name__icontains=q) for q in query_list)) |
            reduce(operator.and_,
                   (Q(country__icontains=q) for q in query_list))
        )
    if query_min_price:
        result = result.filter(Q(price__gte=query_min_price))

    if query_max_price:
        result = result.filter(Q(price__lte=query_max_price))

    return render(request, 'pages/product-list.html', {'product_list': result})

webshop/templates/pages/cart.html
{% extends 'layouts/base.html' %}
{% load humanize %}

{% block content %}

<h2>Cart</h2>
{% if cart.count > 0 %}
<table class="table table-striped">
    <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>In stock</th>
            <th>Unit price</th>
            <th>Discount</th>
            <th>Total price</th>
            <th>Remove</th>
        </tr>
    </thead>

    {% for item in cart %}
    <tr>
        <td>{{ item.product.name }}</td>
        <td>
            <a class="btn btn-primary" href="{% url 'webshop:increase_in_cart' item.object_id item.quantity %}"><i class="fas fa-plus"></i></a>
            {{ item.quantity }}
            <a class="btn btn-primary" href="{% url 'webshop:decrease_in_cart' item.object_id item.quantity %}"><i class="fas fa-minus"></i></a>
        </td>
        <td>{{item.product.stock}}</td>
        <td>${{ item.product.price|intcomma }}</td>
        <td>{{ item.product.discount }}</td>
        <td>${{ item.total_price|intcomma }}</td>
        <td><a class="btn btn-danger" href="{% url 'webshop:remove_from_cart' item.object_id %}"><i class="fas fa-trash-alt fa-xs"></i></a></td>
    </tr>
    {% endfor %}
</table>
<h4>Total price: ${{ cart.summary }}</h4>
<a class="btn btn-primary" href="{% url 'webshop:Buy' %}">Buy</a>
{% else %}
<p>Your cart is empty.</p>

{% endif %}
{% endblock %}

webshop/templates/pages/index.html
{% extends 'layouts/base.html' %}

{% url 'webshop:index' %}
<!-- Entry page for login -->

{% block content %}

  <h1>Sky is not the Limit!</h1>

  <a class="btn btn-primary" href={% url 'webshop:product-list' %}>Start shopping spaceships!</a>

{% endblock %}

webshop/templates/pages/order-list.html
{% extends 'layouts/base.html' %}
{% block content %}

<h2>My orders</h2>


{% if order_list.count > 0 %}
<table class="table table-striped">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Product name</th>
            <th>Status</th>
        </tr>
    </thead>

    {% for order in order_list %}
    <tr>
        <td>{{ order.id }}</td>
        <td>{{ order.product.name }}</td>
        <td>{{ order.status_field }}</td>
    </tr>
    {% endfor %}
</table>

{% else %}
<p>You have no orders yet.</p>

{% endif %}


{% endblock %}

webshop/templates/pages/product-details.html
{% extends 'layouts/base.html' %}
{% load humanize %}
{% block content %}
<h1>{{ product.name }}</h1>
<p>Height: {{ product.height }} m</p>
<p>Brand: {{ product.brand }}</p>
<p>Country: {{ product.country }}</p>
<p>Price: ${{ product.price|intcomma }}</p>
<p>Description: {{ product.description }}</p>
        {% if not product.discount == '-' %}
<p class="card-text" style="color: darkred">Discount: {{ product.discount }}</p>
            {% if not product.discount == '3 for 2' or not product.discount == '2 for 1' %}
<p>Discounted price: ${{ discounted_price|intcomma }}</p>
            {% endif %}
        {% endif %}
 <p>{{ product.stock }} in stock</p>
 <p class="card-text" style="color: darkred">{{ product.errortext }} </p>


<a class="btn btn-primary" href="{% url 'webshop:add_to_cart' product.id %}">Add to cart</a>
<hr />
<a class="btn btn-primary" href={% url 'webshop:product-list' %}>Back to product list</a>
 {% endblock %}

webshop/templates/pages/product-list.html
{% extends 'layouts/base.html' %}
{% load humanize %}
{% block content %}

<h2>Products</h2>
<form method="get" action="{% url 'webshop:product_search_list_view' %}" accept-charset="utf-8">
    <input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
    <input class="searchfield" id="minPrice" name="minprice" type="number" min="0" placeholder="Min Price">
    <input class="searchfield" id="maxPrice" name="maxprice" type="number" min="0" placeholder="Max Price">
    <button class="searchbutton" type="submit">
        <i class="fa fa-search"></i>
    </button>
</form>

  {% for product in product_list %}
    {% if forloop.first %}<div class="row">{% endif %}
      <div class="col-sm-6">
        <div class="card" style="width: 18rem; margin: 20px">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">${{ product.price|intcomma }}</h6>
                <p class="card-text">{{ product.description }}</p>
                {% if not product.discount == '-' %}
                <p class="card-text" style="color: darkred">Discount: {{ product.discount }}</p>
                {% endif %}
                <p class="card-text">{{ product.stock }} left</p>
                <a class="card-link" href="{% url 'webshop:product-details' product.id %}">View</a>
                <a class="card-link" href="{% url 'webshop:add_to_cart' product.id %}">Add to cart</a>
                <p class="card-text" style="color: darkred">{{ product.errortext }} </p>
            </div>
        </div>
      </div>
      {% if forloop.counter|divisibleby:2 %}</div><div class="row">{% endif %}
      {% if forloop.last %}</div>{% endif %}



      {% empty %}
      <li>No products to show.</li>
  {% endfor %}
 {% endblock %}

webshop/templates/pages/purchase-completed.html
{% extends 'layouts/base.html' %}
{% block content %}
<h1>Purchase completed</h1>
<p>Congratulations! Your purchase has been completed.</p>

<hr />

<a class="btn btn-primary" href={% url 'webshop:product-list' %}>Back to product list</a>
 {% endblock %}

webshop/templates/pages/signup.html
{% extends 'layouts/default.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 login-form">
            <h1>Sign up</h1>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                </p>
                {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
                {% endfor %}
                {% endfor %}
                <div class="form-group">
                    <label>Already have an account? </label>
                    <a href="{% url 'login' %}">Login</a>
                </div>
                <button class="btn btn-success btn-block" type="submit">Sign up</button>
            </form>
        </div>
    Please use your valid email as username. This is the email you will receive notifications on.
    </div>
</div>
{% endblock %}